version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/temp_audio:/app/temp_audio
      - ./backend/logs:/app/logs
      - ./backend/models:/app/models
    environment:
      - PYTHONPATH=/app
      - TTS_CACHE_SIZE=50
      - TTS_MODEL_CACHE_SIZE=3
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - NODE_ENV=development
    restart: unless-stopped

volumes:
  voice_data:
  audio_cache:
